#ifndef GUARD_CONSTANTS_COINS_H
#define GUARD_CONSTANTS_COINS_H

#define MAX_COINS 9999
#define COIN_LIMIT_50 (MAX_COINS + 1 - 50)
#define COIN_LIMIT_500 (MAX_COINS + 1 - 500)
#define MAX_COIN_DIGITS 4

#endif // GUARD_CONSTANTS_COINS_H
