#ifndef GUARD_CONSTANTS_FIELD_SPECIALS_H
#define GUARD_CONSTANTS_FIELD_SPECIALS_H

// PC Locations
enum PCLocation
{
    PC_LOCATION_OTHER,
    PC_LOCATION_BRENDANS_HOUSE,
    PC_LOCATION_MAYS_HOUSE,
    PC_LOCATION_PLAYER_HOUSE_FRLG
};

// SS Tidal Locations
enum SSTidalLocation
{
    SS_TIDAL_LOCATION_CURRENTS,
    SS_TIDAL_LOCATION_SLATEPORT,
    SS_TIDAL_LOCATION_LILYCOVE,
    SS_TIDAL_LOCATION_ROUTE124,
    SS_TIDAL_LOCATION_ROUTE131,
};

enum SSTidalState
{
    SS_TIDAL_BOARD_SLATEPORT = 1,
    SS_TIDAL_DEPART_SLATEPORT,
    SS_TIDAL_HALFWAY_LILYCOVE,
    SS_TIDAL_LAND_LILYCOVE,
    SS_TIDAL_BOARD_LILYCOVE,
    SS_TIDAL_DEPART_LILYCOVE,
    SS_TIDAL_HALFWAY_SLATEPORT,
    SS_TIDAL_LAND_SLATEPORT,
    SS_TIDAL_EXIT_CURRENTS_RIGHT,
    SS_TIDAL_EXIT_CURRENTS_LEFT,
};

#define SS_TIDAL_MAX_STEPS 205

// Scrollable Multichoice Menus
enum ScrollMulti
{
    SCROLL_MULTI_NONE,
    SCROLL_MULTI_GLASS_WORKSHOP_VENDOR,
    SCROLL_MULTI_POKEMON_FAN_CLUB_RATER,
    SCROLL_MULTI_BF_EXCHANGE_CORNER_DECOR_VENDOR_1,
    SCROLL_MULTI_BF_EXCHANGE_CORNER_DECOR_VENDOR_2,
    SCROLL_MULTI_BF_EXCHANGE_CORNER_VITAMIN_VENDOR,
    SCROLL_MULTI_BF_EXCHANGE_CORNER_HOLD_ITEM_VENDOR,
    SCROLL_MULTI_BERRY_POWDER_VENDOR,
    SCROLL_MULTI_BF_RECEPTIONIST,
    SCROLL_MULTI_BF_MOVE_TUTOR_1,
    SCROLL_MULTI_BF_MOVE_TUTOR_2,
    SCROLL_MULTI_SS_TIDAL_DESTINATION,
    SCROLL_MULTI_BATTLE_TENT_RULES,
    SCROLL_MULTI_BADGES,
    SCROLL_MULTI_SILPHCO_FLOORS,
    SCROLL_MULTI_CUTTER_MOVE_TUTOR,
    SCROLL_MULTI_WHIP_MOVE_TUTOR,
    SCROLL_MULTI_PUNCH_KICK_MOVE_TUTOR,
    SCROLL_MULTI_FERAL_MOVE_TUTOR,
    SCROLL_MULTI_BIPEDAL_MOVE_TUTOR,
    SCROLL_MULTI_WEATHER_MOVE_TUTOR,
    SCROLL_MULTI_TERRAIN_MOVE_TUTOR,
    SCROLL_MULTI_SIDE_STATUS_MOVE_TUTOR,
    SCROLL_MULTI_SWAP_MOVE_TUTOR,
    SCROLL_MULTI_ROOM_MOVE_TUTOR,
    SCROLL_MULTI_EXPLOSION_MOVE_TUTOR,
    SCROLL_MULTI_GRAB_MOVE_TUTOR,
    SCROLL_MULTI_ULTIMATE_MOVE_TUTOR,
};

#define MAX_SCROLL_MULTI_ON_SCREEN 6
#define MAX_SCROLL_MULTI_LENGTH 16

// Dept Store Floor Numbers
enum DeptStoreFloorNumber
{
    DEPT_STORE_FLOORNUM_B4F,
    DEPT_STORE_FLOORNUM_B3F,
    DEPT_STORE_FLOORNUM_B2F,
    DEPT_STORE_FLOORNUM_B1F,
    DEPT_STORE_FLOORNUM_1F,
    DEPT_STORE_FLOORNUM_2F,
    DEPT_STORE_FLOORNUM_3F,
    DEPT_STORE_FLOORNUM_4F,
    DEPT_STORE_FLOORNUM_5F,
    DEPT_STORE_FLOORNUM_6F,
    DEPT_STORE_FLOORNUM_7F,
    DEPT_STORE_FLOORNUM_8F,
    DEPT_STORE_FLOORNUM_9F,
    DEPT_STORE_FLOORNUM_10F,
    DEPT_STORE_FLOORNUM_11F,
    DEPT_STORE_FLOORNUM_ROOFTOP,
};

// Lilycove Pokémon Trainer Fan Club
#define NUM_TRAINER_FAN_CLUB_MEMBERS  8
#define LAST_NONFAN_MEMBER 7

#define FANCLUB_GOT_FIRST_FANS 7
#define FANCLUB_MEMBER1        8
#define FANCLUB_MEMBER2        9
#define FANCLUB_MEMBER3        10
#define FANCLUB_MEMBER4        11
#define FANCLUB_MEMBER5        12
#define FANCLUB_MEMBER6        13
#define FANCLUB_MEMBER7        14
#define FANCLUB_MEMBER8        15

#define FANCOUNTER_DEFEATED_DRAKE    0
#define FANCOUNTER_BATTLED_AT_BASE   1
#define FANCOUNTER_FINISHED_CONTEST  2
#define FANCOUNTER_USED_BATTLE_TOWER 3

// Return values for DoDeoxysRockInteraction
enum DeoxysRockResult
{
    DEOXYS_ROCK_FAILED,
    DEOXYS_ROCK_PROGRESSED,
    DEOXYS_ROCK_SOLVED,
    DEOXYS_ROCK_COMPLETE,
};

enum {
    OPEN_PARTY_SCREEN,
    NO_PARTY_SCREEN
};

enum {
    CURRENT_POSITION,
    TEMPLATE_POSITION
};

// Starter Pokemon
enum StarterChoice
{
    PC_CHOSE_TREECKO,
    PC_CHOSE_BULBASAUR = PC_CHOSE_TREECKO,
    PC_CHOSE_TORCHIC,
    PC_CHOSE_SQUIRTLE = PC_CHOSE_TORCHIC,
    PC_CHOSE_MUDKIP,
    PC_CHOSE_CHARMANDER = PC_CHOSE_MUDKIP,
};

// Address constants for GetPlayerMaleFemaleString
enum PlayerAddress
{
    ADDR_BIG_GUY,     // Big guy / Big girl
    ADDR_SIR,         // Sir / Ma'am
    ADDR_LAD,         // Lad / Lassie
    ADDR_BOY,         // Boy / Girl
    ADDR_FELLA,       // Fella / Gal
    ADDR_SONNY,       // Sonny / Missy
    ADDR_BRO,         // Bro / Sis
    ADDR_MISTER,      // Mister / Miss
    ADDR_BOYO,        // Boyo / Girlie
    ADDR_CHAMP,       // Champ / Princess
    ADDR_YOUNG_MAN,   // Young man / Young lady
    ADDR_SPORT,       // Sport / Little lady
    ADDR_LADDIE,      // Laddie / Dearie
    ADDR_SON,         // Son / Missy
    ADDR_MAN,         // Man / Girl
    ADDR_MATE,        // Mate / Love
    ADDR_BUDDY,       // Buddy / Pal
    ADDR_CHIEF,       // Chief / Princess
    ADDR_COUNT,
};

#endif // GUARD_CONSTANTS_FIELD_SPECIALS_H
