#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_UNKNOWN,
    SP_NAME_MOM,
    SP_NAME_PLAYER,
    SP_NAME_BRENDAN,
    SP_NAME_MAY,
    SP_NAME_BIRCH,
    SP_NAME_NORMAN,
    SP_NAME_DAD,
    SP_NAME_WALLY,
    SP_NAME_SCOTT,
    SP_NAME_ROXANNE,
    SP_NAME_MR_STONE,
    SP_NAME_WATSON,
    SP_NAME_FLANNERY,
    SP_NAME_WINONA,
    SP_NAME_BRAWLY,
    SP_NAME_TATE,
    SP_NAME_LIZA,
    SP_NAME_TATE_AND_LIZA,
    SP_NAME_JUAN,
    SP_NAME_STEVEN,
    SP_NAME_WALLACE,
    SP_NAME_COURTNEY,
    SP_NAME_MAXIE,
    SP_NAME_TABITHA,
    SP_NAME_MATT,
    SP_NAME_SHELLY,
    SP_NAME_ARCHIE,
    SP_NAME_LANETTE,
    SP_NAME_STERN,
    SP_NAME_COZMO,
    SP_NAME_RYDEL,
    SP_NAME_SIDNEY,
    SP_NAME_PHOEBE, // Leilani
    SP_NAME_GLACIA, // Rosalynn
    SP_NAME_DRAKE,
    SP_NAME_NOLAND,
    SP_NAME_BRANDON, // Roman
    SP_NAME_SPENSER, // Ibrahim
    SP_NAME_LUCY,
    SP_NAME_TUCKER,
    SP_NAME_GRETA,
    SP_NAME_ANABEL,
    SP_NAME_INTERVIEWER,
    SP_NAME_WANDA,
    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
