#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(REST) \
    F(YAWN) \
    F(ENDURE) \
    F(BLOCK_NEW) \
    F(DISABLE) \
    F(WORK_UP) \
    F(REFRESH) \
    F(PROTECT) \
    F(FEINT) \
    F(RETURN) \
    F(FRUSTRATION) \
    F(HELPING_HAND) \
    F(DIRE_OMEN) \
    F(ATTRACT) \
    F(TAUNT) \
    F(EERIE_IMPULSE) \
    F(CHARM) \
    F(FAKE_TEARS) \
    F(ROCK_THROW) \
    F(NATURAL_GIFT) \
    F(CONFUSE_RAY) \
    F(SMACK_DOWN) \
    F(PURSUIT) \
    F(RAPID_SPIN) \
    F(AQUA_RING) \
    F(TRICK) \
    F(INCINERATE) \
    F(KNOCK_OFF) \
    F(ICY_WIND) \
    F(ACID_SPRAY) \
    F(AGILITY) \
    F(BULK_UP) \
    F(CALM_MIND) \
    F(MEDITATE) \
    F(MIST) \
    F(HAZE) \
    F(TAILWIND) \
    F(SAFEGUARD) \
    F(AROMATHERAPY) \
    F(LIFE_DEW) \
    F(HEAL_PULSE) \
    F(FOCUS_ENERGY) \
    F(NASTY_PLOT) \
    F(MYSTICAL_FIRE) \
    F(DIAMOND_DUST) \
    F(CRIPPLE) \
    F(U_TURN) \
    F(SIGNAL_BEAM) \
    F(IRON_DEFENSE) \
    F(SWORDS_DANCE) \
    F(COSMIC_POWER) \
    F(STORED_POWER) \
    F(GIGA_DRAIN) \
    F(CHARGE_BEAM) \
    F(ANCIENT_POWER) \
    F(SILVER_WIND) \
    F(HYPER_VOICE) \
    F(BULLDOZE) \
    F(POWER_GEM) \
    F(DAZZLING_GLEAM) \
    F(POISON_JAB) \
    F(LUNGE) \
    F(PLAY_ROUGH) \
    F(FLAMETHROWER) \
    F(MUD_SHOT) \
    F(THUNDERBOLT) \
    F(ENERGY_BALL) \
    F(ICE_BEAM) \
    F(AURA_SPHERE) \
    F(SLUDGE_BOMB) \
    F(EARTH_POWER) \
    F(PSYCHIC) \
    F(POLLEN_PUFF) \
    F(SHADOW_BALL) \
    F(DRAGON_PULSE) \
    F(DARK_PULSE) \
    F(FLASH_CANNON) \
    F(MOONBLAST) \
    F(WILL_O_WISP) \
    F(THUNDER_WAVE) \
    F(BITTER_COLD) \
    F(TOXIC) \
    F(HYPNOSIS) \
    F(CURSE) \
    F(PETAL_DANCE) \
    F(WISH) \
    F(PERISH_SONG) \
    F(ROAR) \
    F(DEFOG) \
    F(KI_CHARGE) \
    F(DRAGON_DANCE) \
    F(TAKE_DOWN) \
    F(REVERSAL) \
    F(HEAVY_SLAM) \
    F(FIRE_BLAST) \
    F(HYDRO_PUMP) \
    F(AEROBLAST) \
    F(LIMIT_BREAK) \
    F(REVIVAL_BLESSING) \
    F(TAKE_HEART)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
