CableClub_Text_WelcomeWhichCableClubService:
# 1 "data/text/cable_club.pory"
	.string "Welcome to the POKéMON CABLE\n"
	.string "CLUB.\p"
	.string "Which of our services do you wish\n"
	.string "to use?$"

CableClub_Text_WhichService:
# 9 "data/text/cable_club.pory"
	.string "Which of our services do you wish\n"
	.string "to use?$"

CableClub_Text_TradeUsingLinkCable::
# 14 "data/text/cable_club.pory"
	.string "Trade POKéMON with another player\n"
	.string "using a GBA Game Link cable.$"

CableClub_Text_BattleUsingLinkCable::
# 19 "data/text/cable_club.pory"
	.string "You may battle another TRAINER\n"
	.string "using a GBA Game Link cable.$"

CableClub_Text_RecordCornerUsingLinkCable::
# 24 "data/text/cable_club.pory"
	.string "You can use the RECORD CORNER with\n"
	.string "others using a GBA Game Link cable.$"

CableClub_Text_CloseThisMenu:
# 30 "data/text/cable_club.pory"
	.string "Close this menu.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
# 34 "data/text/cable_club.pory"
	.string "For a DOUBLE BATTLE, you must\n"
	.string "have at least two POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
# 39 "data/text/cable_club.pory"
	.string "For trading, you must have at\n"
	.string "least two POKéMON with you.$"

CableClub_Text_CantTradeEnigmaBerry:
# 44 "data/text/cable_club.pory"
	.string "A POKéMON holding the {STR_VAR_1}\n"
	.string "BERRY can't be traded.$"

gText_PleaseWaitForLink::
# 49 "data/text/cable_club.pory"
	.string "Please wait.\n"
	.string "… … B Button: Cancel$"

gText_ConfirmLinkWhenPlayersReady::
# 54 "data/text/cable_club.pory"
	.string "When all players are ready…\n"
	.string "A Button: Confirm\l"
	.string "B Button: Cancel$"

gText_ConfirmStartLinkWithXPlayers::
# 60 "data/text/cable_club.pory"
	.string "Start link with {STR_VAR_1} players.\n"
	.string "A Button: Confirm\l"
	.string "B Button: Cancel$"

gText_AwaitingLinkup::
# 66 "data/text/cable_club.pory"
	.string "Awaiting linkup…\n"
	.string "… … B Button: Cancel$"

CableClub_Text_OkayToSaveProgress::
# 72 "data/text/cable_club.pory"
	.string "Your progress must be saved before\n"
	.string "linking. Is it okay to save?$"

CableClub_Text_PleaseEnter:
# 77 "data/text/cable_club.pory"
	.string "Please enter.$"

CableClub_Text_DirectYouToYourRoom:
# 81 "data/text/cable_club.pory"
	.string "I'll direct you to your room now.$"

Text_SomeoneIsNotReadyToLink:
# 85 "data/text/cable_club.pory"
	.string "Someone is not ready to link.\p"
	.string "Please come back after everyone\n"
	.string "has made preparations.$"

Text_LinkErrorPleaseReset:
# 92 "data/text/cable_club.pory"
	.string "Sorry, we have a link error…\n"
	.string "Please reset and try again.$"

Text_PlayersMadeDifferentSelections:
# 97 "data/text/cable_club.pory"
	.string "The link partners appear to have\n"
	.string "made different selections.$"

CableClub_Text_PleaseVisitAgain:
# 102 "data/text/cable_club.pory"
	.string "Please do visit again.$"

CableClub_Text_IncorrectNumberOfParticipants:
# 106 "data/text/cable_club.pory"
	.string "The number of participants is\n"
	.string "incorrect.$"

CableClub_Text_CantSingleBattleWithXPlayers:
# 111 "data/text/cable_club.pory"
	.string "The SINGLE BATTLE Mode can't be\n"
	.string "played by {STR_VAR_1} players.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
# 116 "data/text/cable_club.pory"
	.string "The DOUBLE BATTLE Mode can't be\n"
	.string "played by {STR_VAR_1} players.$"

CableClub_Text_NeedFourPlayers:
# 121 "data/text/cable_club.pory"
	.string "There must be four players to play\n"
	.string "this Battle Mode.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
# 126 "data/text/cable_club.pory"
	.string "Please confirm the number of\n"
	.string "players and start again.$"

Text_TerminateLinkConfirmation:
# 131 "data/text/cable_club.pory"
	.string "The link will be terminated if you\n"
	.string "leave the room. Is that okay?$"

Text_TerminateLinkPleaseWait:
# 136 "data/text/cable_club.pory"
	.string "Terminating link…\n"
	.string "You will be escorted out of\l"
	.string "the room. Please wait.$"

CableClub_Text_TooBusyToNotice:
# 142 "data/text/cable_club.pory"
	.string "This TRAINER is too busy to\n"
	.string "notice…$"

CableClub_Text_GotToLookAtTrainerCard:
# 147 "data/text/cable_club.pory"
	.string "Score! Got to look at {STR_VAR_1}'s\n"
	.string "TRAINER CARD!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
# 152 "data/text/cable_club.pory"
	.string "Score! Got to look at {STR_VAR_1}'s\n"
	.string "TRAINER CARD!\p"
	.string "It's a {STR_VAR_2} card!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
# 159 "data/text/cable_club.pory"
	.string "Please take your place and start\n"
	.string "your battle.$"

TradeCenter_Text_TakeSeatStartTrade:
# 164 "data/text/cable_club.pory"
	.string "Please take your seat and start\n"
	.string "your trade.$"

RecordCorner_Text_ThanksForComing:
# 169 "data/text/cable_club.pory"
	.string "Thanks for coming.$"

CableClub_Text_TrainerCardDataOverwritten:
# 173 "data/text/cable_club.pory"
	.string "The TRAINER CARD data will\n"
	.string "be overwritten.$"

CableClub_Text_HopeToSeeYouAgain:
# 178 "data/text/cable_club.pory"
	.string "I hope to see you again!$"

CableClub_Text_NotSetUpForFarAwayRegion:
# 182 "data/text/cable_club.pory"
	.string "I'm awfully sorry.\p"
	.string "We're not set up to conduct trades\n"
	.string "with TRAINERS far away in another\l"
	.string "region yet…$"

CableClub_Text_OtherTrainerNotReady:
# 190 "data/text/cable_club.pory"
	.string "The other TRAINER is not ready.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
# 194 "data/text/cable_club.pory"
	.string "You have at least one POKéMON\n"
	.string "that can't be taken.$"

RecordCorner_Text_TakeSeatAndWait:
# 199 "data/text/cable_club.pory"
	.string "Please take your seat and wait.$"

RecordCorner_Text_PlayerSentOverOneX:
# 203 "data/text/cable_club.pory"
	.string "{STR_VAR_1} sent over one\n"
	.string "{STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
# 208 "data/text/cable_club.pory"
	.string "Sorry, there is a transmission error.\p"
	.string "You may not mix records with  \n"
	.string "Japanese Ruby or Sapphire games.\p"
	.string "Also, you can't mix records with\n"
	.string "Japanese Emerald and overseas Ruby\l"
	.string "or Sapphire games at the same time.$"

CableClub_Text_AdapterNotConnected:
# 219 "data/text/cable_club.pory"
	.string "The Wireless Adapter is not\n"
	.string "connected properly.$"

CableClub_Text_ParticipantsStepUpToCounter:
# 224 "data/text/cable_club.pory"
	.string "Participants are asked to step up\n"
	.string "to the reception counter.$"

CableClub_Text_Hello:
# 230 "data/text/cable_club.pory"
	.string "Hello!$"

CableClub_Text_PleaseWait:
# 235 "data/text/cable_club.pory"
	.string "Please wait.$"

CableClub_Text_YouMayTradeHere::
# 239 "data/text/cable_club.pory"
	.string "You may trade your POKéMON here\n"
	.string "with another TRAINER.$"

CableClub_Text_YouMayBattleHere::
# 244 "data/text/cable_club.pory"
	.string "You may battle with your friends\n"
	.string "here.$"

CableClub_Text_CanMakeBerryPowder::
# 249 "data/text/cable_club.pory"
	.string "Two to five TRAINERS can make\n"
	.string "BERRY POWDER together.$"

CableClub_Text_CanMixRecords::
# 254 "data/text/cable_club.pory"
	.string "The records of two to four players\n"
	.string "can be mixed together.$"

CableClub_Text_GuideToVariousServices:
# 260 "data/text/cable_club.pory"
	.string "A guide to the WIRELESS CLUB's\n"
	.string "various services.$"

CableClub_Text_CancelSelectedItem::
# 265 "data/text/cable_club.pory"
	.string "Cancels the selected MENU item.$"

CableClub_Text_WhichBattleMode:
# 270 "data/text/cable_club.pory"
	.string "Which battle mode would you like?$"

CableClub_Text_ReturnsToPreviousStep:
# 275 "data/text/cable_club.pory"
	.string "Returns to the previous step.$"

CableClub_Text_NeedBerryForBerryCrush:
# 279 "data/text/cable_club.pory"
	.string "To use the BERRY CRUSH service,\n"
	.string "you must have at least one BERRY.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
# 284 "data/text/cable_club.pory"
	.string "To enter the UNION ROOM, you must\n"
	.string "have at least two POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
# 289 "data/text/cable_club.pory"
	.string "No POKéMON holding the {STR_VAR_1}\n"
	.string "BERRY may enter the UNION ROOM.$"

CableClub_Text_UnionRoomAdapterNotConnected:
# 294 "data/text/cable_club.pory"
	.string "This is the POKéMON WIRELESS CLUB\n"
	.string "UNION ROOM.\p"
	.string "Unfortunately, your Wireless\n"
	.string "Adapter is not connected properly.\p"
	.string "Please do come again.$"

CableClub_Text_OhExcuseMe:
# 305 "data/text/cable_club.pory"
	.string "Oh…\n"
	.string "Excuse me!$"

CableClub_Text_PlayerIsWaiting:
# 310 "data/text/cable_club.pory"
	.string "It appears as if {STR_VAR_1} is playing\n"
	.string "right now.\l"
	.string "Go for it!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
# 316 "data/text/cable_club.pory"
	.string "I can explain game rules to you,\n"
	.string "if you'd like.\p"
	.string "Which game should I describe?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
# 323 "data/text/cable_club.pory"
	.string "“POKéMON JUMP”\p"
	.string "Make your POKéMON skip the VINE WHIP\n"
	.string "rope with the A Button.\p"
	.string "Only mini POKéMON around 28 inches\n"
	.string "or less may participate.\p"
	.string "POKéMON that only swim, burrow,\n"
	.string "or fly are not good at jumping.\p"
	.string "As a result, those POKéMON may not\n"
	.string "participate.\p"
	.string "Good things happen if everyone\n"
	.string "jumps in time.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
# 342 "data/text/cable_club.pory"
	.string "“DODRIO BERRY-PICKING”\p"
	.string "Command DODRIO's three heads to\n"
	.string "catch falling BERRIES.\p"
	.string "Press right, up, or left on the\n"
	.string "{PLUS} Control Pad to move the heads.\p"
	.string "To play this game, you must have\n"
	.string "a DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
# 355 "data/text/cable_club.pory"
	.string "If you want to play a game,\n"
	.string "please tell the old man beside me.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
# 360 "data/text/cable_club.pory"
	.string "Hi, welcome!\n"
	.string "Are you here to play games using\l"
	.string "Wireless Communication?\p"
	.string "Can you wait just a little bit?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
# 368 "data/text/cable_club.pory"
	.string "All right, come again!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
# 372 "data/text/cable_club.pory"
	.string "The Wireless Adapter isn't connected.\n"
	.string "Come back when it's hooked up!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
# 377 "data/text/cable_club.pory"
	.string "All right, which game did you want\n"
	.string "to play?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
# 382 "data/text/cable_club.pory"
	.string "Which POKéMON would you like to\n"
	.string "enter?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
# 387 "data/text/cable_club.pory"
	.string "Okay, you're all good to go.\n"
	.string "Don't let the others beat you!$"

MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
# 393 "data/text/cable_club.pory"
	.string "Are you leaving now?\n"
	.string "Do come again!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
# 398 "data/text/cable_club.pory"
	.string "It doesn't look like you have any\n"
	.string "POKéMON that you can enter…\p"
	.string "Would you like me to explain what\n"
	.string "kinds of POKéMON can enter?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
# 406 "data/text/cable_club.pory"
	.string "“POKéMON JUMP” is open to POKéMON\n"
	.string "around 28 inches or less.\p"
	.string "What you can't enter are those\n"
	.string "POKéMON that can't jump.\p"
	.string "You know, like POKéMON that only\n"
	.string "swim, burrow, or fly.\p"
	.string "That's all you need to know.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
# 419 "data/text/cable_club.pory"
	.string "DODRIO BERRY-PICKING is a game that \n"
	.string "only DODRIO may enter.$"

MossdeepCity_GameCorner_1F_Text_RetryPlease:
# 425 "data/text/cable_club.pory"
	.string "Could you retry this from the start\n"
	.string "again, please?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
# 430 "data/text/cable_club.pory"
	.string "Welcome to the POKéMON WIRELESS\n"
	.string "CLUB DIRECT CORNER.\p"
	.string "You may interact directly with\n"
	.string "your friends here.\p"
	.string "Which room would you like to\n"
	.string "enter?$"

CableClub_Text_TradePokemon:
# 441 "data/text/cable_club.pory"
	.string "Would you like to trade POKéMON?$"

CableClub_Text_PlayWhichBattleMode:
# 445 "data/text/cable_club.pory"
	.string "Which Battle Mode would you like\n"
	.string "to play?$"

CableClub_Text_AccessRecordCorner:
# 450 "data/text/cable_club.pory"
	.string "Would you like to access\n"
	.string "the RECORD CORNER?$"

CableClub_Text_UseBerryCrush:
# 455 "data/text/cable_club.pory"
	.string "Would you like to use the\n"
	.string "BERRY CRUSH System?$"

CableClub_Text_ExplainBattleModes:
# 460 "data/text/cable_club.pory"
	.string "There are three Battle Modes.\p"
	.string "SINGLE BATTLE is for two TRAINERS\n"
	.string "with one or more POKéMON each.\p"
	.string "Each TRAINER can have one POKéMON\n"
	.string "in battle at a time.\p"
	.string "DOUBLE BATTLE is for two TRAINERS\n"
	.string "with two or more POKéMON each.\p"
	.string "Each TRAINER will send out two\n"
	.string "POKéMON in battle at a time.\p"
	.string "MULTI BATTLE is for four TRAINERS\n"
	.string "with one or more POKéMON each.\p"
	.string "Each TRAINER can have one POKéMON\n"
	.string "in battle at a time.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
# 482 "data/text/cable_club.pory"
	.string "Please decide which of you two\n"
	.string "will become the LEADER.\p"
	.string "The other player must then choose\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeaderOfFour:
# 490 "data/text/cable_club.pory"
	.string "Please decide which of you four\n"
	.string "will become the GROUP LEADER.\p"
	.string "The other players must then choose\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeader:
# 498 "data/text/cable_club.pory"
	.string "Please decide which of you will\n"
	.string "become the GROUP LEADER.\p"
	.string "The other players must then choose\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_WelcomeUnionRoomEnter:
# 506 "data/text/cable_club.pory"
	.string "Welcome to the POKéMON WIRELESS\n"
	.string "CLUB UNION ROOM.\p"
	.string "You may interact directly with\n"
	.string "other TRAINERS here, some of\l"
	.string "whom you may not even know.\p"
	.string "Would you like to enter the ROOM?$"

CableClub_Text_UnionRoomInfo:
# 517 "data/text/cable_club.pory"
	.string "The TRAINERS in the UNION ROOM\n"
	.string "will be those players around you\l"
	.string "who have also entered the ROOM.\p"
	.string "You may do all sorts of things\n"
	.string "here, such as exchanging greetings.\p"
	.string "You may enter two POKéMON up to\n"
	.string "Lv. 30 for a one-on-one battle.\p"
	.string "You may take part in a chat with\n"
	.string "two to five people.\p"
	.string "Or, you may register a POKéMON for\n"
	.string "trade.\p"
	.string "Would you like to enter the ROOM?$"

CableClub_Text_EnjoyUnionRoom:
# 537 "data/text/cable_club.pory"
	.string "I hope you enjoy your time in\n"
	.string "the UNION ROOM.$"

CableClub_Text_FirstTimeRightThisWay:
# 542 "data/text/cable_club.pory"
	.string "Hello!\n"
	.string "My name is TEALA.\p"
	.string "This must be your first time\n"
	.string "up here.\p"
	.string "I'll show you how the Wireless\n"
	.string "Communication System works.\p"
	.string "First, I need to show you this\n"
	.string "floor of our POKéMON CENTER.\p"
	.string "Right this way, please.$"

CableClub_Text_ExplainWirelessClubFirstTime:
# 558 "data/text/cable_club.pory"
	.string "On the top floor, there are two\n"
	.string "rooms.\p"
	.string "First, the room on the left.\n"
	.string "It's the UNION ROOM.\p"
	.string "You may link up with TRAINERS\n"
	.string "around you who have also entered\l"
	.string "the UNION ROOM.\p"
	.string "With them, you may do things like\n"
	.string "chat, battle, and trade.\p"
	.string "Second, the room on the right is\n"
	.string "the DIRECT CORNER.\p"
	.string "You may trade or battle POKéMON\n"
	.string "with your friends in this room.\p"
	.string "If the Wireless Adapter isn't\n"
	.string "connected, you may still link up\l"
	.string "using a GBA Game Link cable.\p"
	.string "If that is the case, you must go\n"
	.string "to the DIRECT CORNER.\p"
	.string "I hope you enjoy the Wireless \n"
	.string "Communication System.$"

CableClub_Text_AskAboutLinking:
# 589 "data/text/cable_club.pory"
	.string "Hello, {PLAYER}!\p"
	.string "It's me, TEALA, the POKéMON\n"
	.string "CENTER 2F attendant.\p"
	.string "Is there something you needed to\n"
	.string "ask me about linking?$"

CableClub_Text_ExplainWirelessClub:
# 599 "data/text/cable_club.pory"
	.string "Let me explain how the POKéMON\n"
	.string "WIRELESS CLUB works.\p"
	.string "On this, the top floor, there are\n"
	.string "two rooms.\p"
	.string "First, the room on the left.\n"
	.string "It's the UNION ROOM.\p"
	.string "You may link up with TRAINERS\n"
	.string "around you who have also entered\l"
	.string "the UNION ROOM.\p"
	.string "With them, you may do things like\n"
	.string "chat, battle, and trade.\p"
	.string "Second, the room on the right is\n"
	.string "the DIRECT CORNER.\p"
	.string "You may trade or battle POKéMON\n"
	.string "with your friends in this room.\p"
	.string "Sometimes, you may not be able to\n"
	.string "find your friends in the UNION ROOM\l"
	.string "or the DIRECT CORNER.\p"
	.string "In that case, please move closer\n"
	.string "to your friends.\p"
	.string "If the Wireless Adapter isn't\n"
	.string "connected, you may still link up\l"
	.string "using a GBA Game Link cable.\p"
	.string "If that is the case, you must go\n"
	.string "to the DIRECT CORNER.\p"
	.string "I hope you enjoy the Wireless \n"
	.string "Communication System.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
# 640 "data/text/cable_club.pory"
	.string "I hope you enjoy the Wireless\n"
	.string "Communication System.$"
