Text_PictureBookShelf:
# 1 "data/text/check_furniture.pory"
	.string "There's a set of POKéMON picture books.$"

Text_BookShelf:
# 5 "data/text/check_furniture.pory"
	.string "It's filled with all sorts of books.$"

Text_PokemonCenterBookShelf:
# 9 "data/text/check_furniture.pory"
	.string "POKéMON magazines!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "ADORABLE POKéMON…$"

Text_Vase:
# 17 "data/text/check_furniture.pory"
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan:
# 24 "data/text/check_furniture.pory"
	.string "It's empty.$"

Text_ShopShelf:
# 28 "data/text/check_furniture.pory"
	.string "The shelves brim with all sorts of\n"
	.string "POKéMON merchandise.$"

Text_Blueprint:
# 33 "data/text/check_furniture.pory"
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
