LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
# 1 "data/text/lottery_corner.pory"
	.string "This is the POKéMON LOTTERY CORNER.\p"
	.string "All shoppers at our DEPARTMENT STORE\n"
	.string "get to draw a POKéMON LOTO TICKET.\p"
	.string "If the LOTO TICKET's number matches\n"
	.string "the ID number of any of your POKéMON,\l"
	.string "you will receive a fabulous gift.\p"
	.string "Would you like to draw a POKéMON\n"
	.string "LOTO TICKET?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
# 15 "data/text/lottery_corner.pory"
	.string "Please come back tomorrow.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
# 19 "data/text/lottery_corner.pory"
	.string "Please do visit again.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
# 23 "data/text/lottery_corner.pory"
	.string "Please pick a LOTO TICKET.\n"
	.string "…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
# 28 "data/text/lottery_corner.pory"
	.string "The LOTO TICKET number is {STR_VAR_1}.\p"
	.string "I need to run a check on this number\n"
	.string "to see if it matches any of your\l"
	.string "POKéMON's ID numbers. Please wait.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
# 36 "data/text/lottery_corner.pory"
	.string "Congratulations!\p"
	.string "The ID number of your team's\n"
	.string "{STR_VAR_1} matches your\l"
	.string "LOTO TICKET's number!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
# 44 "data/text/lottery_corner.pory"
	.string "Congratulations!\p"
	.string "The ID number of your PC-boxed\n"
	.string "{STR_VAR_1} matches your\l"
	.string "LOTO TICKET's number!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
# 52 "data/text/lottery_corner.pory"
	.string "I'm sorry.\n"
	.string "None of the numbers matched.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
# 57 "data/text/lottery_corner.pory"
	.string "Two digits matched, so you win the\n"
	.string "third prize!\l"
	.string "You've won the {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
# 63 "data/text/lottery_corner.pory"
	.string "Three digits matched, so you win the\n"
	.string "second prize!\l"
	.string "You've won the {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
# 69 "data/text/lottery_corner.pory"
	.string "Four digits matched, so you win the\n"
	.string "first prize!\l"
	.string "You've won the {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
# 75 "data/text/lottery_corner.pory"
	.string "Oh, my goodness, all five digits\n"
	.string "matched!\p"
	.string "You've won the jackpot prize!\n"
	.string "You've won the {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
# 83 "data/text/lottery_corner.pory"
	.string "Oh?\n"
	.string "You seem to have no room for this.\p"
	.string "Please make room in your BAG and\n"
	.string "let me know.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
# 91 "data/text/lottery_corner.pory"
	.string "{PLAYER}?\n"
	.string "Yes, I've been expecting you.\p"
	.string "This is the prize we've been holding\n"
	.string "for you.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
# 99 "data/text/lottery_corner.pory"
	.string "Please do visit again.$"
