MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce::
# 1 "data/text/move_tutors.pory"
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"

MoveTutor_Text_SwaggerTeach::
# 6 "data/text/move_tutors.pory"
	.string "As a POKéfan, I really don't like hurting\n"
	.string "POKéMON when I go to catch them.\p"
	.string "It is a necessity however, so I\n"
	.string "developed a technique to inflict as \l"
	.string "little pain as possible.\p"
	.string "Want me to teach your POKéMON how?$"

MoveTutor_Text_SwaggerDeclined::
# 17 "data/text/move_tutors.pory"
	.string "What do you just like to hurt POKéMON\n"
	.string "or something?\p"
	.string "You should try being a better person.$"

MoveTutor_Text_SwaggerWhichMon::
# 24 "data/text/move_tutors.pory"
	.string "Wow, you're such a good person like me.\n"
	.string "Which POKéMON should I do first?$"

MoveTutor_Text_SwaggerTaught::
# 29 "data/text/move_tutors.pory"
	.string "Good luck, catching more POKéMON and\n"
	.string "battling other trainers with them!$"

MoveTutor_Text_RolloutTeach::
# 34 "data/text/move_tutors.pory"
	.string "What are you looking at, huh?\p"
	.string "It's because I'm fat, is that it?\p"
	.string "You know animals fatten up before\n"
	.string "hibernating for a reason!\p"
	.string "You know what, I can teach you and your\n"
	.string "POKéMON a thing or two if you want?$"

MoveTutor_Text_RolloutDeclined::
# 46 "data/text/move_tutors.pory"
	.string "That's just what I'd expect from a skin\n"
	.string "and bones loser like you!$"

MoveTutor_Text_RolloutWhichMon::
# 51 "data/text/move_tutors.pory"
	.string "Glad to see you're learning tolerance.\n"
	.string "Which one should I teach, then?$"

MoveTutor_Text_RolloutTaught::
# 56 "data/text/move_tutors.pory"
	.string "That should help your POKéMON, but you\n"
	.string "should put on some pounds yourself.$"

MoveTutor_Text_FuryCutterTeach::
# 61 "data/text/move_tutors.pory"
	.string "I taught my CHIMCHAR to throw berries\n"
	.string "at my sister.\p"
	.string "It's really funny!\p"
	.string "If you want, I can teach your POKéMON\n"
	.string "how to do it too!$"

MoveTutor_Text_FuryCutterDeclined::
# 71 "data/text/move_tutors.pory"
	.string "You have a lowsy sense of humor...$"

MoveTutor_Text_FuryCutterWhichMon::
# 75 "data/text/move_tutors.pory"
	.string "Yay!\n"
	.string "Show me which POKéMON I should teach.$"

MoveTutor_Text_FuryCutterTaught::
# 80 "data/text/move_tutors.pory"
	.string "Picking the right berry is the first key\n"
	.string "to success!$"

MoveTutor_MimicTeach::
# 85 "data/text/move_tutors.pory"
	.string "Isn't it cool that I can swallow an\n"
	.string "entire hot dog in a single bite?\p"
	.string "I could teach you if you want.\p"
	.string "No, huh?\n"
	.string "Well, how about I teach one of your\l"
	.string "POKéMON instead, then?$"

MoveTutor_MimicDeclined::
# 96 "data/text/move_tutors.pory"
	.string "Come on, man. I'm just trying to share\n"
	.string "my amazing talents with the world...$"

MoveTutor_Text_MimicWhichMon::
# 101 "data/text/move_tutors.pory"
	.string "Nice!\n"
	.string "Which one are we doing, then?$"

MoveTutor_Text_MimicTaught::
# 106 "data/text/move_tutors.pory"
	.string "Yeah, your POKéMON is already a master!\p"
	.string "You could show it off in battle if you\n"
	.string "had some food stashed.$"

MoveTutor_Text_MetronomeTeach::
# 113 "data/text/move_tutors.pory"
	.string "What do you want?\n"
	.string "I'm try to buy some food, here.\p"
	.string "What's that?\n"
	.string "You're here to buy food as well?\p"
	.string "You're thinking right, kid.\n"
	.string "The more you eat, the more energy your\l"
	.string "body can EXPEND.\p"
	.string "If you want, I can teach your POKéMON\n"
	.string "how to best EXPEND their energy.$"

MoveTutor_Text_MetronomeDeclined::
# 128 "data/text/move_tutors.pory"
	.string "That's a shame.\n"
	.string "I thought we were on the same page.$"

MoveTutor_Text_MetronomeWhichMon::
# 133 "data/text/move_tutors.pory"
	.string "Good man!\n"
	.string "Which POKéMON, then?$"

MoveTutor_Text_MetronomeTaught::
# 138 "data/text/move_tutors.pory"
	.string "There you go, then.\p"
	.string "You know, using your POKéMON's energy\n"
	.string "effectively could be the difference\l"
	.string "between winning or losing a battle.$"

MoveTutor_Text_SleepTalkTeach::
# 146 "data/text/move_tutors.pory"
	.string "Humph! My wife relies on HIDDEN\n"
	.string "POWER to stay awake.\p"
	.string "She should just take a nap like I do,\n"
	.string "and SLEEP TALK.\p"
	.string "I can teach your POKéMON how to\n"
	.string "SLEEP TALK instead. Interested?$"

MoveTutor_Text_SleepTalkDeclined::
# 157 "data/text/move_tutors.pory"
	.string "Oh, fine, fine. You want to stay awake\n"
	.string "with HIDDEN POWER, too…$"

MoveTutor_Text_SleepTalkWhichMon::
# 162 "data/text/move_tutors.pory"
	.string "Ah, an appreciative child!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_SleepTalkTaught::
# 167 "data/text/move_tutors.pory"
	.string "I've never once gotten my wife's\n"
	.string "coin trick right.\p"
	.string "I would be happy if I got it right\n"
	.string "even as I SLEEP TALK…$"

MoveTutor_Text_SubstituteTeach::
# 175 "data/text/move_tutors.pory"
	.string "When I see the wide world from up\n"
	.string "here on the roof…\p"
	.string "I think about how nice it would be\n"
	.string "if there were more than just one me\l"
	.string "so I could enjoy all sorts of lives.\p"
	.string "Of course it's not possible.\n"
	.string "Giggle…\p"
	.string "I know! Would you be interested in\n"
	.string "having a POKéMON learn SUBSTITUTE?$"

MoveTutor_Text_SubstituteDeclined::
# 190 "data/text/move_tutors.pory"
	.string "Oh, no?\p"
	.string "A POKéMON can make a copy of\n"
	.string "itself using it, you know.$"

MoveTutor_Text_SubstituteWhichMon::
# 197 "data/text/move_tutors.pory"
	.string "Giggle…\n"
	.string "Which POKéMON do you want me to\l"
	.string "teach SUBSTITUTE?$"

MoveTutor_Text_SubstituteTaught::
# 203 "data/text/move_tutors.pory"
	.string "We human beings should enjoy our\n"
	.string "own lives to the utmost!\p"
	.string "I hope you'll get that way, too!$"

MoveTutor_Text_DynamicPunchTeach::
# 210 "data/text/move_tutors.pory"
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a FIGHTING-type TRAINER,\n"
	.string "so I can't win at the MOSSDEEP GYM\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Or do you want me to teach your\n"
	.string "POKéMON DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined::
# 229 "data/text/move_tutors.pory"
	.string "Darn! You're even making fun of me?\n"
	.string "Punch! Punch! Punch!$"

MoveTutor_Text_DynamicPunchWhichMon::
# 234 "data/text/move_tutors.pory"
	.string "What? You do? You're a good person!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_DynamicPunchTaught::
# 239 "data/text/move_tutors.pory"
	.string "I want you to win at the MOSSDEEP GYM\n"
	.string "using that DYNAMICPUNCH!$"

MoveTutor_Text_DoubleEdgeTeach::
# 244 "data/text/move_tutors.pory"
	.string "Sigh…\p"
	.string "SOOTOPOLIS's GYM LEADER is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "He's got appeal with a DOUBLE-EDGE.\n"
	.string "I couldn't even catch his eye.\p"
	.string "Please, let me teach your POKéMON\n"
	.string "the move DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined::
# 260 "data/text/move_tutors.pory"
	.string "Oh…\n"
	.string "Even you rejected me…$"

MoveTutor_Text_DoubleEdgeWhichMon::
# 265 "data/text/move_tutors.pory"
	.string "Okay, which POKéMON should I teach\n"
	.string "DOUBLE-EDGE?$"

MoveTutor_Text_DoubleEdgeTaught::
# 270 "data/text/move_tutors.pory"
	.string "I won't live for love anymore!\n"
	.string "I'll become tough!$"

MoveTutor_Text_ExplosionTeach::
# 275 "data/text/move_tutors.pory"
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge EXPLOSION of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "teach EXPLOSION to your POKéMON!$"

MoveTutor_Text_ExplosionDeclined::
# 289 "data/text/move_tutors.pory"
	.string "Gaah! You're turning me down because\n"
	.string "I live in the country?$"

MoveTutor_Text_ExplosionWhichMon::
# 294 "data/text/move_tutors.pory"
	.string "Fine! An EXPLOSION it is!\n"
	.string "Which POKéMON wants to blow up?$"

MoveTutor_Text_ExplosionTaught::
# 299 "data/text/move_tutors.pory"
	.string "For a long time, I've taught POKéMON\n"
	.string "how to use EXPLOSION, but I've yet\l"
	.string "to ignite my own EXPLOSION…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"
