gText_ObtainedTheItem::
# 1 "data/text/obtain_item.pory"
	.string "Obtained the {STR_VAR_2}!$"

gText_TheBagIsFull::
# 5 "data/text/obtain_item.pory"
	.string "The BAG is full…$"

gText_PutItemInPocket::
# 9 "data/text/obtain_item.pory"
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3} POCKET.$"

gText_PlayerFoundOneItem::
# 14 "data/text/obtain_item.pory"
	.string "{PLAYER} found one {STR_VAR_2}!$"

gText_TooBadBagIsFull::
# 18 "data/text/obtain_item.pory"
	.string "Too bad!\n"
	.string "The BAG is full…$"

gText_PlayerPutItemInBag::
# 23 "data/text/obtain_item.pory"
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the BAG.$"

gText_ObtainedTheDecor::
# 28 "data/text/obtain_item.pory"
	.string "Obtained the {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
# 32 "data/text/obtain_item.pory"
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
# 37 "data/text/obtain_item.pory"
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"

gText_ObtainedTheItems::
# 42 "data/text/obtain_item.pory"
	.string "Obtained {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
# 46 "data/text/obtain_item.pory"
	.string "{PLAYER} found {STR_VAR_1} {STR_VAR_2}!$"

gText_PutCoinsAwayInCoinCase::
# 50 "data/text/obtain_item.pory"
	.string "{PLAYER} put the COINS away in\n"
	.string "the COIN CASE.$"

gText_FoundXCoins::
# 55 "data/text/obtain_item.pory"
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_FoundXItems::
# 60 "data/text/obtain_item.pory"
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

gText_CoinCaseIsFull::
# 65 "data/text/obtain_item.pory"
	.string "Too bad!\n"
	.string "The COIN CASE is full…$"

gText_NothingToPutThemIn::
# 70 "data/text/obtain_item.pory"
	.string "Too bad!\n"
	.string "There's nothing to put them in…$"
