Route25_Frlg_MapScripts::
	.byte 0


Route25_EventScript_SeaCottageSign::
# 4 "data/maps/Route25_Frlg/scripts.pory"
	msgbox Route25_Text_SeaCottageSign, MSGBOX_SIGN
	end


Route25_EventScript_Man::
# 9 "data/maps/Route25_Frlg/scripts.pory"
	msgbox Route25_Text_AreYouHereAlone, MSGBOX_NPC
	end


Route25_Text_JoeyIntro::
# 13 "data/maps/Route25_Frlg/scripts.pory"
	.string "Local TRAINERS come here to\n"
	.string "practice.$"

Route25_Text_JoeyDefeat::
# 18 "data/maps/Route25_Frlg/scripts.pory"
	.string "You're decent.$"

Route25_Text_JoeyPostBattle::
# 22 "data/maps/Route25_Frlg/scripts.pory"
	.string "All POKéMON have weaknesses.\n"
	.string "Even the strongest ones.\p"
	.string "That's why it's best to raise\n"
	.string "POKéMON of different types.$"

Route25_Text_DanIntro::
# 30 "data/maps/Route25_Frlg/scripts.pory"
	.string "Dad took me to a great party on\n"
	.string "the S.S. ANNE at VERMILION CITY.$"

Route25_Text_DanDefeat::
# 35 "data/maps/Route25_Frlg/scripts.pory"
	.string "I'm not mad!$"

Route25_Text_DanPostBattle::
# 39 "data/maps/Route25_Frlg/scripts.pory"
	.string "On the S.S. ANNE, I saw TRAINERS\n"
	.string "from around the world.$"

Route25_Text_FlintIntro::
# 44 "data/maps/Route25_Frlg/scripts.pory"
	.string "I'm a cool guy.\n"
	.string "I've got a girlfriend!$"

Route25_Text_FlintDefeat::
# 49 "data/maps/Route25_Frlg/scripts.pory"
	.string "Aww, darn…$"

Route25_Text_FlintPostBattle::
# 53 "data/maps/Route25_Frlg/scripts.pory"
	.string "Oh, well.\n"
	.string "My girlfriend will cheer me up.$"

Route25_Text_KelseyIntro::
# 58 "data/maps/Route25_Frlg/scripts.pory"
	.string "Hi!\n"
	.string "My boyfriend is cool!$"

Route25_Text_KelseyDefeat::
# 63 "data/maps/Route25_Frlg/scripts.pory"
	.string "My conditioning isn't the best…$"

Route25_Text_KelseyPostBattle::
# 67 "data/maps/Route25_Frlg/scripts.pory"
	.string "I wish my boyfriend was as good\n"
	.string "as you.$"

Route25_Text_ChadIntro::
# 72 "data/maps/Route25_Frlg/scripts.pory"
	.string "I had this feeling…\n"
	.string "I knew I had to battle you!$"

Route25_Text_ChadDefeat::
# 77 "data/maps/Route25_Frlg/scripts.pory"
	.string "I knew I'd lose, too!$"

Route25_Text_ChadPostBattle::
# 81 "data/maps/Route25_Frlg/scripts.pory"
	.string "If your POKéMON gets confused,\n"
	.string "switch it out.\p"
	.string "That's a good tactic.$"

Route25_Text_HaleyIntro::
# 88 "data/maps/Route25_Frlg/scripts.pory"
	.string "My friend has many cute POKéMON.\n"
	.string "I'm so jealous!$"

Route25_Text_HaleyDefeat::
# 93 "data/maps/Route25_Frlg/scripts.pory"
	.string "I'm not so jealous!$"

Route25_Text_HaleyPostBattle::
# 97 "data/maps/Route25_Frlg/scripts.pory"
	.string "You came from MT. MOON?\n"
	.string "May I have a CLEFAIRY?$"

Route25_Text_FranklinIntro::
# 102 "data/maps/Route25_Frlg/scripts.pory"
	.string "I just got down from MT. MOON,\n"
	.string "but I've still got gas in the tank!$"

Route25_Text_FranklinDefeat::
# 107 "data/maps/Route25_Frlg/scripts.pory"
	.string "You worked hard!$"

Route25_Text_FranklinPostBattle::
# 111 "data/maps/Route25_Frlg/scripts.pory"
	.string "Drat!\n"
	.string "A ZUBAT bit me back in that cave.$"

Route25_Text_NobIntro::
# 116 "data/maps/Route25_Frlg/scripts.pory"
	.string "I'm off to see a POKéMANIAC's\n"
	.string "collection at the cape.$"

Route25_Text_NobDefeat::
# 121 "data/maps/Route25_Frlg/scripts.pory"
	.string "You done got me, and real good,\n"
	.string "too!$"

Route25_Text_NobPostBattle::
# 126 "data/maps/Route25_Frlg/scripts.pory"
	.string "The POKéMANIAC sure lives up to\n"
	.string "his name.\p"
	.string "His collection includes many rare\n"
	.string "species of POKéMON.$"

Route25_Text_WayneIntro::
# 134 "data/maps/Route25_Frlg/scripts.pory"
	.string "You're going to see BILL?\n"
	.string "First, we battle!$"

Route25_Text_WayneDefeat::
# 139 "data/maps/Route25_Frlg/scripts.pory"
	.string "You're something.$"

Route25_Text_WaynePostBattle::
# 143 "data/maps/Route25_Frlg/scripts.pory"
	.string "The trail below is a shortcut to\n"
	.string "CERULEAN CITY.$"

Route25_Text_SeaCottageSign::
# 148 "data/maps/Route25_Frlg/scripts.pory"
	.string "SEA COTTAGE\n"
	.string "BILL lives here!$"

Route25_Text_MistyHighHopesAboutThisPlace::
# 153 "data/maps/Route25_Frlg/scripts.pory"
	.string "This cape is a famous date spot.\p"
	.string "MISTY, the GYM LEADER, has high\n"
	.string "hopes about this place.$"

Route25_Text_AreYouHereAlone::
# 160 "data/maps/Route25_Frlg/scripts.pory"
	.string "Hello, are you here alone?\p"
	.string "If you're out at CERULEAN's cape…\n"
	.string "Well, it should be as a couple.$"
