Route17_Frlg_MapScripts::
	.byte 0


Route17_EventScript_ItemsNotice::
# 4 "data/maps/Route17_Frlg/scripts.pory"
	msgbox Route17_Text_WatchOutForDiscardedItems, MSGBOX_SIGN
	end


Route17_EventScript_TrainerTips1::
# 9 "data/maps/Route17_Frlg/scripts.pory"
	msgbox Route17_Text_SameSpeciesGrowDifferentRates, MSGBOX_SIGN
	end


Route17_EventScript_TrainerTips2::
# 14 "data/maps/Route17_Frlg/scripts.pory"
	msgbox Route17_Text_PressBToStayInPlace, MSGBOX_SIGN
	end


Route17_EventScript_RouteSign::
# 19 "data/maps/Route17_Frlg/scripts.pory"
	msgbox Route17_Text_RouteSign, MSGBOX_SIGN
	end


Route17_EventScript_BallsNotice::
# 24 "data/maps/Route17_Frlg/scripts.pory"
	msgbox Route17_Text_DontThrowGameThrowBalls, MSGBOX_SIGN
	end


Route17_EventScript_CyclingRoadSign::
# 29 "data/maps/Route17_Frlg/scripts.pory"
	msgbox Route17_Text_CyclingRoadSign, MSGBOX_SIGN
	end


Route17_Text_RaulIntro::
# 33 "data/maps/Route17_Frlg/scripts.pory"
	.string "There's no getting rich quick in\n"
	.string "battling kids.$"

Route17_Text_RaulDefeat::
# 38 "data/maps/Route17_Frlg/scripts.pory"
	.string "Burned out!$"

Route17_Text_RaulPostBattle::
# 42 "data/maps/Route17_Frlg/scripts.pory"
	.string "You can find good stuff lying\n"
	.string "around on CYCLING ROAD.\p"
	.string "There's good money in picking them\n"
	.string "up and selling them.$"

Route17_Text_IsaiahIntro::
# 50 "data/maps/Route17_Frlg/scripts.pory"
	.string "I'm mighty proud of my bod, kiddo.\n"
	.string "Come on!$"

Route17_Text_IsaiahDefeat::
# 55 "data/maps/Route17_Frlg/scripts.pory"
	.string "Whoo!$"

Route17_Text_IsaiahPostBattle::
# 59 "data/maps/Route17_Frlg/scripts.pory"
	.string "I could belly-bump you outta\n"
	.string "here!$"

Route17_Text_VirgilIntro::
# 64 "data/maps/Route17_Frlg/scripts.pory"
	.string "You heading to FUCHSIA?$"

Route17_Text_VirgilDefeat::
# 68 "data/maps/Route17_Frlg/scripts.pory"
	.string "Crash and burn!$"

Route17_Text_VirgilPostBattle::
# 72 "data/maps/Route17_Frlg/scripts.pory"
	.string "I love racing downhill!$"

Route17_Text_BillyIntro::
# 76 "data/maps/Route17_Frlg/scripts.pory"
	.string "We're BIKERS!\n"
	.string "We rule the roads, man!$"

Route17_Text_BillyDefeat::
# 81 "data/maps/Route17_Frlg/scripts.pory"
	.string "Smoked!$"

Route17_Text_BillyPostBattle::
# 85 "data/maps/Route17_Frlg/scripts.pory"
	.string "Are you looking for adventure?$"

Route17_Text_NikolasIntro::
# 89 "data/maps/Route17_Frlg/scripts.pory"
	.string "Let VOLTORB electrify you!$"

Route17_Text_NikolasDefeat::
# 93 "data/maps/Route17_Frlg/scripts.pory"
	.string "Grounded out!$"

Route17_Text_NikolasPostBattle::
# 97 "data/maps/Route17_Frlg/scripts.pory"
	.string "I got my VOLTORB at the abandoned\n"
	.string "POWER PLANT.$"

Route17_Text_ZeekIntro::
# 102 "data/maps/Route17_Frlg/scripts.pory"
	.string "I leveled up my POKéMON, but it\n"
	.string "won't evolve. Why?$"

Route17_Text_ZeekDefeat::
# 107 "data/maps/Route17_Frlg/scripts.pory"
	.string "Why, you!$"

Route17_Text_ZeekPostBattle::
# 111 "data/maps/Route17_Frlg/scripts.pory"
	.string "Maybe some POKéMON need element\n"
	.string "STONES to evolve.$"

Route17_Text_JamalIntro::
# 116 "data/maps/Route17_Frlg/scripts.pory"
	.string "I need a little exercise!$"

Route17_Text_JamalDefeat::
# 120 "data/maps/Route17_Frlg/scripts.pory"
	.string "Whew!\n"
	.string "Good workout!$"

Route17_Text_JamalPostBattle::
# 125 "data/maps/Route17_Frlg/scripts.pory"
	.string "I'm sure I lost weight there!$"

Route17_Text_CoreyIntro::
# 129 "data/maps/Route17_Frlg/scripts.pory"
	.string "Be a rebel!$"

Route17_Text_CoreyDefeat::
# 133 "data/maps/Route17_Frlg/scripts.pory"
	.string "Aaaargh!$"

Route17_Text_CoreyPostBattle::
# 137 "data/maps/Route17_Frlg/scripts.pory"
	.string "Be ready to fight for your beliefs!$"

Route17_Text_JaxonIntro::
# 141 "data/maps/Route17_Frlg/scripts.pory"
	.string "Nice BIKE!\n"
	.string "How's it handle?$"

Route17_Text_JaxonDefeat::
# 146 "data/maps/Route17_Frlg/scripts.pory"
	.string "Shoot!$"

Route17_Text_JaxonPostBattle::
# 150 "data/maps/Route17_Frlg/scripts.pory"
	.string "The slope makes it hard to steer.$"

Route17_Text_WilliamIntro::
# 154 "data/maps/Route17_Frlg/scripts.pory"
	.string "Get lost, kid!\n"
	.string "I'm bushed!$"

Route17_Text_WilliamDefeat::
# 159 "data/maps/Route17_Frlg/scripts.pory"
	.string "Are you satisfied?$"

Route17_Text_WilliamPostBattle::
# 163 "data/maps/Route17_Frlg/scripts.pory"
	.string "I need to catch a few z's!$"

Route17_Text_WatchOutForDiscardedItems::
# 167 "data/maps/Route17_Frlg/scripts.pory"
	.string "It's a notice.\p"
	.string "Watch out for discarded items.$"

Route17_Text_SameSpeciesGrowDifferentRates::
# 173 "data/maps/Route17_Frlg/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "All POKéMON are unique.\p"
	.string "Even POKéMON of the same species\n"
	.string "and level grow at different rates.$"

Route17_Text_PressBToStayInPlace::
# 182 "data/maps/Route17_Frlg/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Press the B Button to stay in place\n"
	.string "while on a slope.$"

Route17_Text_RouteSign::
# 189 "data/maps/Route17_Frlg/scripts.pory"
	.string "ROUTE 17\n"
	.string "CELADON CITY - FUCHSIA CITY$"

Route17_Text_DontThrowGameThrowBalls::
# 194 "data/maps/Route17_Frlg/scripts.pory"
	.string "It's a notice!\p"
	.string "Don't throw the game, throw POKé\n"
	.string "BALLS instead!$"

Route17_Text_CyclingRoadSign::
# 201 "data/maps/Route17_Frlg/scripts.pory"
	.string "CYCLING ROAD\n"
	.string "Slope ends here!$"
