@ Starting from here, these movements are considered
@ 'safe' (won't put follower into a Pokeball)
Common_Movement_FollowerSafeStart::
Common_Movement_QuestionMark:
	emote_question_mark
	step_end

Common_Movement_ExclamationMark:
	emote_exclamation_mark
	step_end

Common_Movement_Delay48:
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_FacePlayer:
	face_player
	step_end

Common_Movement_FaceAwayPlayer:
	face_away_player
	step_end

Common_Movement_FaceOriginalDirection:
	face_reset
	step_end

Common_Movement_StepFasterLeft:
	step_faster_left
	step_end

Common_Movement_StepFasterUp:
	step_faster_up
	step_end

Common_Movement_StepFasterRight:
	step_faster_right
	step_end

Common_Movement_StepFasterDown:
	step_faster_down
	step_end

Common_Movement_FaceRight::
	face_right
	step_end

Common_Movement_FaceLeft::
	face_left
	step_end

Common_Movement_FaceDown::
	face_down
	step_end

Common_Movement_FaceUp::
	face_up
	step_end

Common_Movement_StepDown:
	step_down
	step_end

Common_Movement_StepLeft:
	step_left
	step_end

Common_Movement_StepRight:
	step_right
	step_end

@ End of follower-safe movements
Common_Movement_FollowerSafeEnd::
	step_end
	
Common_Movement_WalkUp5::
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_WalkUp6:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_WalkUp4:
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_Delay32:
	delay_16
	delay_16
	step_end

Common_Movement_WalkUp::
	walk_up
	step_end

@ Unused
Common_Movement_WalkUp2::
	walk_up
	walk_up
	step_end

@ Follower NPC
Common_Movement_CreepUp::
	creep_up
	step_end

Common_Movement_CreepDown::
	creep_down
	step_end

Common_Movement_CreepRight::
	creep_right
	step_end

Common_Movement_CreepLeft::
	creep_left
	step_end

Common_Movement_WalkDown::
	walk_down
	step_end

Common_Movement_WalkRight::
	walk_right
	step_end

Common_Movement_WalkLeft::
	walk_left
	step_end

Common_Movement_RunUp::
	run_up
	step_end

Common_Movement_RunDown::
	run_down
	step_end

Common_Movement_RunRight::
	run_right
	step_end

Common_Movement_RunLeft::
	run_left
	step_end

Common_Movement_SprintUp::
	sprint_up
	step_end

Common_Movement_SprintDown::
	sprint_down
	step_end

Common_Movement_SprintRight::
	sprint_right
	step_end

Common_Movement_SprintLeft::
	sprint_left
	step_end
